### ISSUE TITLE
Initiate battles with other players

### ISSUE THREAD

**Issue by Salgat** [Salgat/Testing#6]
The best example I can find is the Ghost Marowak script, where you walk at a certain location that starts a spontaneous battle. 

https://github.com/pret/pokered/blob/4634304dcebf055ed0e1cab171c2d28e66399763/scripts/pokemontower6.asm#L24

Another good one is copying this script https://github.com/pret/pokered/blob/8a5a7d8e68538b727e0c166488265f395603366e/home.asm#L2293

We could use someone like Oak as the target trainer and hook all reads to Oak's data as whatever the simulated player's pokemon are. From there, we will need to hook all decisions made by the AI with what the player is doing. Or better yet, perhaps define an unused section of memory as a new trainer with the remote player's pokemon and have the wTrainerHeaderPtr point to that memory location.

**Comment by Salgat** [comment]
To start a trainer battle,

mmu.WriteByte(0xd057, 0x2); // wIsInBattle
    mmu.WriteByte(0xd05a, 0x0); // wBattleType
    mmu.WriteByte(0xd059, 247); // wCurOpponent
    mmu.WriteByte(0xd713, 247); // wEnemyMonOrTrainerClass
    mmu.WriteByte(0xd05d, 1); // wTrainerNo

wCurOpponent is found at TrainerDataPointers where YoungsterData (the first) is at 201 and wTrainerNo indicates which index in that wCurOpponent type to choose (starting at 1 for the first)

**Comment by Salgat** [comment]
https://github.com/pret/pokered/blob/351146024bdd386c328af0f2abdb04e728e4c133/engine/battle/trainer_ai.asm

For the AI, what we can do which might be the easiest way is to pause the game right after your move is made, then when the remote player makes his move, set all four available moves to the move the remote player selected, so that the AI has to choose that. The only issue now is how to handle ranges; may have to hook into that somehow, maybe it's based on some random value we can force to a value.

**Comment by Salgat** [comment]
It looks like we can use these values

wPlayerSelectedMove -> wEnemySelectedMove
wMoveMissed
wMoveDidntMiss
wPlayerMoveEffect -> wEnemyMoveEffect
wDamage
wPartyMons -> wEnemyMons (maybe)

PlayerCalcMoveDamage is where this is called. We can write guard the above values to control what move is taken, what damage is done, etc. We can also use Green3Data for our trainer, and temporarily override the pokemon data with the levels and species of pokemon of the remote player. Will also need to override name temporarily with the name of the remote player.

**Comment by Salgat** [comment]
5e646ab31e5adf03d895460cfb4e678af1751ca1 adds a "debug" option where Q saves the enemy pokemon party, W overrides the enemy pokemon party with the saved, and E is used after the enemy pokemon party is loaded. Using this logic, we can save the current pokemon party, serialize it, then send it to the remote player to load the pokemon.

**Comment by Salgat** [comment]
Need to add the option now that if you press A when facing a player adjacent to you, input is disabled and you can select between BATTLE and TRADE or cancel (B).

**Comment by Salgat** [comment]
Now need to, upon initiating battle, send a battle request to remote player. If he agrees, he sends back a response and both players override wEnemyMons with the remote player and start a trainer battle.

Need to add dialogue for accepting or refusing a battle request. If the player is already in a dialogue, respond back with a busy response.

**Comment by asalgat** [comment]
Need to disable dialogue when in any battle, otherwise you keep initiating dialogue after you start a battle while facing someone.

**Comment by Salgat** [comment]
In a remote battle, need to add a flag that checks when a certain memory is read, then pauses the game to wait for the remote player. It looks like the two memory locations we care about are "selectPlayerMove" and "selectEnemyMove" and "wEnemySelectedMove" and "wPlayerSelectedMove". 

What we can do is whenever we reach "selectEnemyMove", the player's move is already done, so we can pause the game and send our move to the remote player. He can also do the same. Once we receive his move, we override "wEnemySelectedMove" with the remote player's "wPlayerSelectedMove" and continue.

NOTE: Will need to share an initial seed between both players and override random values with predetermined random values. Not sure yet how the order of the random values being called will work.

**Comment by Salgat** [comment]
I believe we also need to copy over wActionResultOrTookBattleTurn and wWhichPokemon and, for the enemy only, override wActionResultOrTookBattleTurn and wWhichPokemon with the remote player's values.

It looks like there is ExecuteEnemyMove and ExecutePlayerMove. If wActionResultOrTookBattleTurn is true for switching monster, right after "SelectEnemyMove" is called in the "MainInBattleLoop",  change the Program Counter to https://github.com/pret/pokered/blob/master/engine/battle/core.asm#L434 and set wSerialExchangeNybbleReceiveData to 0xFF. It will trick the game into thinking a linked player has switched pokemon, and switch pokemon. Be sure at this point to have wActionResultOrTookBattleTurn and wWhichPokemon overridden.

The address after the call "SelectEnemyMove" is 0x3C2A9 which is bank 0xF offset 0x42a9. At this point, if wanting to switch pokemon, change program counter to this. An easy way to do this is in the CPU logic do a "if PC == bank 0xF offset 0x42a9 then PC = 0x3C2B0 (bank 0xF offset 0x42b0)" which is where it loads the wSerialExchangeNybbleReceiveData value (which is set to 0xFF).

Note: We don't have to worry about timing since both wActionResultOrTookBattleTurn and wWhichPokemon are already set by the time we reach "SelectEnemyMove".

**Comment by Salgat** [comment]
So it currently works, but unfortunately the pokemon makes a move automatically after switching. We want that switch to take up the whole turn, so we need to figure out how to skip his turn.

https://github.com/pret/pokered/blob/master/engine/battle/core.asm#L3033 0xFF in wEnemySelectedMove may be able to tell it that you can't select a move.

**Comment by Salgat** [comment]
Battling with pokemon switching now works. Next up is to synchronize BattleRandom calls to return the same value and to disable item selection. 

For item selection, one way is to ignore "A" button presses when the cursor is over the item menu. If that doesn't work, may be able to temporarily activate "link mode" which does not allow items.

For battlerandom, can send each player a seed and manually override the battle random value with a predetermined random number.

**Comment by Salgat** [comment]
When pressing the A button, ignore it if in a network battle and wBattleAndStartSavedMenuItem == 1

EDIT: Unfortunately this doesn't work, so I am going the hacky route for now and simply looking at the screen to see if it's there.

**Comment by Salgat** [comment]
With select ITEM now being ignored, finally need to synchronize battlerandom. 

It looks like rdiv (0xff04) is exclusively used in Pokemon for random number generation. This is a counter based off a frequency of 16384Hz which means we can override ReadByte(0xff04) with pre-determined values between 0-255. When initiating a battle, the initiator provides a random seed for both players to use. All subsequent 0xff04 reads (while in network battle) return a random value using that provided seed. I don't believe there is a situation where random calls can be done out of order in a battle so there shouldn't be any issues with desynching the random. 

There is still some desynch between clients, which I'm guessing might be due to AI. Need to only override random calls that are directly related to battle. The easiest way to do this is to not check for when BattleRandom is called, but for when the code reaches a valid location where BattleRandom will be called. AI decision logic for example will be ignored for this. We will include a list of all locations we think BattleRandom should be synched for and just keep modifying the list till we synchronize the random calls properly.

**Comment by Salgat** [comment]
It seems that there is a desync that occurs specifically for H_MULTIPLICAND and its related memory locations. Now need to investigate what is causing these values to desync. (Note, these values may be simply be set by these functions differently due to other external variables) Also, could be a possibly that we're still missing battle random calls.

EDIT: While I synchronized random, I've hit an issue. Basically, both the remote and local game states think their the player vs a trainer, which causes an issue where, when things like equal speed occur, both sides think they go first or second. Might have to force the game to, for certain things, think it's playing a remote player to fix this issue. 

The following in the battle engine do link state checks.
- selectEnemyMove - probably not needed
- EnemyRan - probably not needed
- ReplaceFaintedEnemyMon - probably not needed
- TrainerBattleVictory - probably not needed
- ChooseNextMon - probably not needed
- HandlePlayerBlackOut - probably not needed
- EnemySendOutFirstMon - probably not needed
- TryRunningFromBattle - probably not needed
- upperLeftMenuItemWasNotSelected - probably not needed
- selectedmoveknown - probably not needed
- SelectEnemyMove - should be fine, probably not needed
- CheckForDisobedience - needed but can be addressed later
- GetEnemyMonStat - this one might be important
- ExecuteEnemyMove - maybe
- LoadEnemyMonData - probably needed
- ApplyBadgeStatBoosts - probably needed (to not apply boosts)
- BattleRandom - already addressed
- StatModifierDownEffect - probably needed
- MimicEffect - probably needed, but later
- pickMoveToDisable - not sure

Additionally, in engine/battle/trainer_ai.asm
- TrainerAI - Can probably use this to ignore any extra actions taken by the trainer
- SwitchEnemyMon - Same as before

One way to utilize this, is when a certain function is called, trigger a flag for the next wLinkState read to be equal to LINK_STATE_BATTLING then clear the flag.

**Comment by Salgat** [comment]
After a lot of trial and error, pinpointed the issue down to two things,
1. wLinkState has to be enabled for certain calls such as LoadEnemyMonFromParty where you'd otherwise have the incorrect pokemon stats (their stats would be autogenerated instead of calculated based on transmitted EVs among other things). This created a huge desynch very quickly.
2. Address 0xffaa holds connection information based on who is the connection "host" and "client". This is important for one single reason, it resolves situations where both pokemon have equal speed and a determination on who goes first has to be made.

From here, the last major thing to get battles fully working is to populate missing variables expected for LoadEnemyMonFromParty such as the Pokemon's nickname.

**Comment by notchris** [comment]
I developed a web UI that may work nicely for this project. I'm not sure if this is the correct place to comment but I'm happy to share it!

**Comment by asalgat** [comment]
Hey @notchris! I'd love to check it out, do you have a fork or repo that I can look at?

**Comment by notchris** [comment]
I can get that setup when I'm home from work, but here are some previews - completely html/css & touch actions mapped. 
![screenshot 2016-03-01 06 00 38](https://cloud.githubusercontent.com/assets/1944433/13641266/d05c6218-e5e5-11e5-94f1-bb5a3e77407e.png)

![screenshot 2016-02-13 12 52 19](https://cloud.githubusercontent.com/assets/1944433/13641277/d510ab66-e5e5-11e5-90a7-9f569fa8d703.png)

**Comment by asalgat** [comment]
Looks great but I'm curious how you are mapping this to a C++ emulator?

**Comment by notchris** [comment]
Well I'm using a javascript emulator for GB. So far no one has really built a usable emulator that works completely in mobile browser. I've been able to get almost everything working except sound and save states (though I'm close, just need to switch method). Seems to be working on iOS decently, gameplay is normal speed.

**Comment by asalgat** [comment]
Ahhh I see what you mean. Yeah while this project is a C++ project, the modifications made can definitely be ported over to a JS based emulator (the networking part would especially be made easier). While I unfortunately don't have the time to do a full port (I'm wrapping up what I'm doing with this project which should be complete this week), I will provide assistance needed if someone else wants to do it. It would be very cool to have a web based multiplayer version of Pokemon Red/Blue/Yellow.

**Comment by notchris** [comment]
Awesome! Well, maybe you can help me out with the save state portion, I have a few ideas of how to go about doing it, but it's been a little difficult.

**Comment by asalgat** [comment]
For save states on the GameBoy, there are two ways to do it. If you just want to create a .SAV file you save a raw $a000-$a1ff and then load those same values when you boot the Game Boy back up (this is what the game boy does for creating save files). Mind you, you'll also need to store RTC data after it if you want to preserve the clock also.

For creating a true save state, you save the entire RAM memory (which is 0x0000-0x00FF and 0x4000-0xFFFF) and simply write that back to memory when loading the save state. In both cases you can either save these to a file or save them to LocalStorage.

http://gameboy.mongenel.com/dmg/asmmemmap.html
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by notchris** [comment]
The emulator seems to create save states as a typed-array. The size of the localstorage value is generally about 3-4mb, not exceeding the limit of most mobile browsers. Localstorage will save the array as a string, but mobile browsers seems to save the localstorage in the cache, which is not ideal. I was considering creating a file by converting the typed array to a Blob, but I do not have that fully working. Does it seem odd to you that the savestate is so large?

**Comment by asalgat** [comment]
My save states are about 150kb and that's because they are stored inefficiently, 3-4MB seems excessively large unless they are also saving the game ROM too?

**Comment by notchris** [comment]
No kidding! Well then they must be including the rom file. Do you hang out on IRC at all?

**Comment by notchris** [comment]
I'm going to look into this save-state filesize issue. I'm not sure if the js emulator requires the gamefile to be part of the array.

**Comment by notchris** [comment]
You were right about the save states! They ended up being 150kb or less, thank you.

**Comment by asalgat** [comment]
That's awesome to hear! Shoot me a link when you get a stable version running on a website.

**Comment by notchris** [comment]
Check out: http://tiny.cc/o2n09x

**Comment by Salgat** [comment]
Save state seems to work great, although unfortunately the controls don't seem to work yet (not sure if you're still implementing that?)

As a side note,  synchronized battling now works so I am closing this issue.
